rocket/rocket

.gitignore

I've created a gitignore rule for build (out-of-ource) direcotries of QtCreator, which is the default settings. Due I'm using this repo as a subrepo inside my project, it's pretty annoying that git is trying to commit build files, so I've added this rule.

Gitignore for build directory under windows

---

lib/base.h
lib/device.c

Now this should work better. Some caching issue failed to permanently delete my previous fork and then was later overwritten :\

Compile fix: warnings for VS2012 (+x64) and up.

---

editor/editor.pro
editor/mainwindow.cpp
editor/mainwindow.h
editor/syncclient.cpp
editor/syncclient.h
editor/syncdocument.h

SyncClient is a much better name, because the socket-ism of the
client is an implementation detail, not a required part of the
interface of the base-class. So let's generalize this a bit so
we don't leak needless details.
While we're at it, tweak includes of the header a bit for minimal
recompilation.

editor: rename ClientSocket to SyncClient

---

lib/device.c

We're about to free the storage of this variable anyway, so the
assign does little useful.

player: remove pointless assign

---

lib/device.c

Noticed by Valgrind. This one is a bit nasty as the file-descriptor
could be reused by the system, and we could end up closing random
file-descriptors as a result.

player: do not use closed socket fd

---

lib/device.c

The last argument to strncat isn't the total amount of characters
the buffer have room for, but the maximum number of bytes we can
append to the string. This means we need to subtract the amount
already appended.
Spotted by clang-checker.

player: fix strncat usage

---

examples/example_bass.cpp
lib/device.c
lib/sync.h

We might add more transports, so let's not use the generic name sync_connect for TCP.

Rename sync_connect to sync_tcp_connect

---

.travis.yml

Qt4 doesn't contain QWebSockets, which is required for JavaScript
support. So let's use Qt5 instead.

travis-ci: use qt5 instead of qt4

---

appveyor.yml

Since we've switched to using bass from NuGet, there's no point in this
any more.

appveyor: do not download bass

---

lib/base.h

When redefining preprocessor defines, they need to exactly match
the previous definition to prevent warnings from being generated.
And if we use the project settings to set _CRT_SECURE_NO_WARNINGS
and/or _CRT_NONSTDC_NO_DEPRECATE, MSVC defines them to "1". So
let's make sure our definition matches what MSVC uses.

player: use redef-friendly defines

---

README.md
contrib/logo.svg
editor/mainwindow.cpp
js/README.md
js/package.json

This project is not a part of the GNU-project, and the old GNU
Rocket joke isn't really that funny. So let's avoid confusion for
outsiders, and just talk about "Rocket" instead of "GNU Rocket".
There's still some cases that have been left due to backwards
compatibility. I might try to write some transitional code at some
later point, but for now this is a step in the right direction.

remove needless GNU-mentions

---

.travis.yml

Seems macdeployqt is highly flawed in the qt5 brew-package, and
doesn't do everything we need. In particular, the frame-references
inside the Qt libraries themselves are not relative to the
application itself. So let's just roll up our sleeves and do it
ourselves.

travis: fixup paths to frameworks

---

editor/syncdocument.cpp

In the unlikely event of a power-outage or similar sudden
interruption while the document is writing to disk, it's better to
save to a temp-file and atomically rename that file to the new one
instead of leaving a half-written file on disk.
However, this has several subtleties to it that I don't really want
to have to deal with myself, so let's just use the Qt 5.1 QSaveFile
API for this. This means that older Qt versions will have to live
with the slightly less robust solution for now.

editor: use QSaveFile if available

---

editor/trackview.cpp

Taking the address of the first element is invalid when the QVector
is empty, and Qt will trigger an assertion on this in debug-builds.
Luckily, it's completely benign in release-builds, which is what
most people use. But let's make sure we don't annoy those users who
do trigger this, by discarding all their changes!

editor: fix crash in debug-build

---

editor/syncpage.cpp

This was a silly slip-up; we definately need to invalidate the key
that was deleted, no matter what the interpolation mode was.

editor: invalidate deleted keyframe

---

.travis.yml

It seems Travis now already have coreutils installed on their osx
builders. And since brew doesn't seem to have an easy-to-use flag
to skip installing installed packages, and instead spews an error,
let's just drop installing the package in the first place.

travis: do not install coreutils

---

README.md

Let's point at our own license-file rather than the copy at
opensource.org.
While we're at it, let's have shields.io pick the license from the github
API, instead of specifying. This means there's less things that needs to
be changed if we ever decided to relicence. Not that there's any plans for
that.

README: change around the license-badge a bit

---

editor/mainwindow.cpp

In 435c884 ("editor: allow navigation while playing"), I forgot that
other pages needs the same update as well. So let's just pipe that
through.
We can safely do it here, because this setter is treated as a
non-navigation row-change, which means that it will not emit an
editRowChanged(int) signal in response.

editor: update other track-pages when navigating

---

editor/mainwindow.cpp

In the recent row-setting refactorings, it seems this code got
left over. It even produces a warning for me, so let's terminate
it.

editor: kill dead code

---

lib/device.c

@mrautio: I think this does roughly what we need to allow path-separators again, yet staying a bit safe. I left out windows-style path-separators, to keep things cross-platform. What do you think?

Allow path separators

---

editor/mainwindow.cpp

Some demos can send rather small packets and the network can also do
anything, so loop until the whole length of the greeting is available.
Stop waiting if an error has occurred though.

Wait until the demo has sent the whole greeting

---

editor/editor.cpp

Since Qt 5.6, hash-tables are stored in randomized order. This leads to
visible changes in .rocket-files, because QtXml uses hash-tables to
store XML-atributes.
The long term solution would probably be to drop Qt4 support, and move
to QXmlStreamReader / QXmlStreamWriter instead, but for now we can just
fix the hash-seed.

editor: make sure .rocket-files are stored consistently

---

.travis.yml
README.md
editor/editor.pro

Qt 6 is planned to be released at the end of the year, and the Qt 4 support is somewhat crippled (missing websocket support). I think it's time to drop the Q4 support. This will allow us to embrace Qt 5 features more in the code-base, and should reduce the need to jump through hoops.

Drop Qt 4.x support

---

editor/mainwindow.cpp
editor/mainwindow.h

The lifetime of the TrackViews is somehow complicated to keep track of,
and when we're setting the document, we end up trying to disconnect
signals from a TrackView that's currently being deleted.
This is no big deal, as all Qt does is emit a warning and move on. But
it's even nicer to avoid this warning, and we can do that in a pretty
simple way without having to change the code much; by storing the
connection object and disconnecting that instead.
So let's do that. This gets us rid of these three warnings whenever we
load a new document:
QObject::disconnect: No such signal QObject::posChanged(int, int)
QObject::disconnect: No such signal QObject::editRowChanged(int)
QObject::disconnect: No such signal QObject::currValDirty()

editor: store connection objects for some signals/slots

---

README.md

The rust implementation of rocket has been moved to a new home on github, edited the README.md file to reflect this.

Updated README.md with new repo URL

---

.travis.yml

The macOS CI build was broken, primarily because brew no longer provides a bottle for SDL versions this old.
While we're at it, also simplify the CI setup a bit, so we would have seen the right problem as an error message instead.
Fixes: #82

Fix TravisCI macOS build

---

.github/workflows/ci.yml

We get a few warnings due to using old, deprecated actions. We should upgrade things!
This also affects #91, which adds a use of `actions/checkout@v2`.

ci: upgrade actions

---

.github/workflows/ci.yml

This only builds the editor, because we don't have VS2008 on GitHub actions.
It's probably about time to change to change to a build-system that doesn't need upgrading the project files every time we compile with a different compiler, so let's leave it at that for now.

ci: add windows build

---

.github/workflows/ci.yml

No clue if this actually works, but at least it's not missing the root directory, which is what the actual app-bundle is.

macos: upload dmg macos artifact instead of broken app-bundle

---

.github/workflows/ci.yml

Installing Qt takes an unreasonably long time on Windows, so let's enable the internal cache for this.
While we're at it, also disable installing QtCreator, which we don't use.

ci: cache windows-deps

---

Makefile
lib/device.h
lib/librocket.vs2008.vcproj
lib/librocket.vs2013.vcxproj

This is compile-only tested, but considering the code is fairly oportunistic, it should probably just work.

set USE_NODELAY on windows builds

---

lib/device.c

There's no good reason to pass a char instead of an int here, and if we don't, we have to add a cast. Let's just pass the int all the way through.

player: fix implicit cast warning

---

.github/workflows/ci.yml

Otherwise, apt might be looking for stale versions, which can be pruned from the server.

ci: run apt-get update

---

Makefile
lib/device.c
lib/device.h
lib/librocket.vs2008.vcproj
lib/librocket.vs2013.vcxproj
lib/sync.h
lib/tcp.c

This series introduces an abstract socket IO mechanism for callers implementing their own communications handling.
The existing sync_tcp_connect()/sync_connect() functions are refactored to share this underlying abstraction, resulting in better separation of the network code from core Rocket protocol handling code.

Abstract socket communcations behind a callback interface
